server:
  port: 9081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: desafio-veiculos

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:veiculos_db}
    username: ${DB_USER:user}
    password: ${DB_PASS:pass}
  jpa:
    hibernate:
      ddl-auto: validate 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: analysis-log-persister
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "br.com.desafio.veiculos.domain" 
        
  logging:
    level:
      br.com.desafio: INFO
      org.springframework.web: INFO
    pattern:
      json: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%p","thread":"%t","logger":"%C","traceId":"%X{traceId}","spanId":"%X{spanId}","idempotencyKey":"%X{idempotencyKey}","vin":"%X{vin}","message":"%m"}%n'


app:
  
  integration:
    normalization:
      url: ${NORMALIZATION_API_URL:https://api.apibrasil.io/placa/v2}
      token: ${NORMALIZATION_API_TOKEN:SEU_TOKEN_AQUI}
    f1:
      url: ${F1_SOAP_URL:http://localhost:9090/ws/f1} 
    f2:
      url: ${F2_REST_URL:http://localhost:9090/api/f2}
    f3:
      url: ${F3_REST_URL:http://localhost:9090/api/f3}

  executor:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 1000

resilience4j:
  
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50 
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20 
        minimumNumberOfCalls: 10 
        waitDurationInOpenState: 10s 
        permittedNumberOfCallsInHalfOpenState: 5
        
  retry:
    configs:
      default:
        maxAttempts: 3 
        waitDuration: 200ms 
        retryExceptions:
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
          - br.com.desafio.veiculos.domain.exception.InfrastructureException
        
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 10 

  ratelimiter:
    configs:
      f1_limiter:
        limitForPeriod: 2 
        limitRefreshPeriod: 1s
        timeoutDuration: 100ms 

  
  instances:
    
    F1:
      baseConfig: default
      waitDurationInOpenState: 15s 
    F1-rate:
      baseConfig: f1_limiter      

    F2:
      baseConfig: default
      
    F3:
      baseConfig: default
  
    NORMALIZATION:
      baseConfig: default
      slidingWindowSize: 50 
      waitDurationInOpenState: 5s